
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  name = "code.cloudfoundry.org/bytefmt"
  branch = "master"

[[constraint]]
  name = "github.com/DATA-DOG/godog"
  version = "0.7.6"

[[constraint]]
  name = "github.com/Knetic/govaluate"
  version = "3.0.0"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "v8"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/google/go-github"
  branch = "master"

[[constraint]]
  name = "github.com/hellofresh/health-go"
  version = "1.2.6"

[[constraint]]
  name = "github.com/hellofresh/logging-go"
  version = "0.1.6"

[[constraint]]
  name = "github.com/hellofresh/stats-go"
  version = "0.8.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  revision = "b4575eea38cca1123ec2dc90c26529b5c5acfcff"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.4.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/tidwall/gjson"
  version = "1.1.0"

[[constraint]]
  name = "github.com/ulule/limiter"
  version = "2.0.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.12.0"

[[constraint]]
  branch = "master"
  name = "github.com/rafaeljesus/retry-go"

[[constraint]]
  name = "github.com/felixge/httpsnoop"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/afex/hystrix-go"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/globalsign/mgo"
  version = "r2018.04.23"
